server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: catalog-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
resilience4j:
  circuitbreaker:
    instances:
      movie-service:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 15000
        permitted-number-of-calls-in-half-open-state: 3
        register-health-indicator: true
        allow-health-indicator-to-fail: false
        automatic-transition-from-open-to-half-open-enabled: true
      serie-service:
        sliding-window-type: TIME_BASED
        sliding-window-size: 10s
        failure-rate-threshold: 50
        wait-duration-in-open-state: 15000
        register-health-indicator: true
        allow-health-indicator-to-fail: false
        automatic-transition-from-open-to-half-open-enabled: true
