server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      database: catalog
      port: 27018
  application:
    name: catalog-service
  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: false
    binding:
      listener:
        simple:
          queues:
            - name: ${queue.movie.name}
            - name: ${queue.serie.name}
    queues:
      - name: ${queue.movie.name}
        durable: true
      - name: ${queue.serie.name}
        durable: true
    host: localhost
    port: 5672
    username: guest
    password: guest

queue:
  movie:
    name: MovieQueue
  serie:
    name: SerieQueue

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
management:
    endpoints:
        web:
            exposure:
                include: '*'
    health:
        circuitbreakers:
            enabled: true
    endpoint:
        health:
            show-details: always
resilience4j:
  circuitbreaker:
    instances:
      movie-service:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        allowHealthIndicatorToFail: false
        automaticTransitionFromOpenToHalfOpenEnabled: true
      serie-service:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        allowHealthIndicatorToFail: false
        automaticTransitionFromOpenToHalfOpenEnabled: true
        
